apiVersion: apps/v1
kind: Deployment
metadata:
  name: doom
  labels:
    app: doom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doom
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: doom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - name: doom
        image: storaxdev/kubedoom:0.5.0
        ports:
        - containerPort: 5900
          protocol: TCP
